### ISSUE TITLE
数据插入异常

### ISSUE THREAD

**Issue by pw2ust** [leftjs/StudentGradesManageSystem#1]
学生信息和成绩数据插入有异常，麻烦你能不能改一下，救Java萌新。=。=

**Comment by leftjs** [comment]
具体哪一段代码，能详细指出么，或者bug截图，两年前的项目，有点记不得了

**Comment by pw2ust** [comment]
能给个联系方式吗？方便点

**Comment by leftjs** [comment]
你直接在github上提就可以了

**Comment by pw2ust** [comment]
在以admin登陆以后添加学生信息后，出现以下错误
``` java
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.njupt.sms.utils.StudentInfoUtils.saveStudentInfoByMap(StudentInfoUtils.java:122)
	at com.njupt.sms.ui.HomeAdmin$StudentInfoModel.saveStudentTable(HomeAdmin.java:515)
	at com.njupt.sms.ui.HomeAdmin$9.actionPerformed(HomeAdmin.java:222)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.jav

```

**Comment by leftjs** [comment]
`For input string: ""` 不知道你是否正确录入了age，如果信息完整并且正确应该不会出现空字符串
