### ISSUE TITLE
运行报错，详情见图

### ISSUE THREAD

**Issue by terrytan95** [leftjs/StudentGradesManageSystem#3]
`Exception in thread "main" java.lang.NullPointerException
	at com.njupt.sms.ui.Login.<init>(Login.java:31)
	at Main.main(Main.java:18)
`

**Comment by leftjs** [comment]
where picture?

**Comment by terrytan95** [comment]
It's done, thanks

**Comment by OranGeCCG** [comment]
how did you solved this problem?

**Comment by A152468** [comment]
为什么程序运行报错

**Comment by zhangchengyi46** [comment]
Exception in thread "main" java.lang.NullPointerException
	at com.njupt.sms.ui.Login.<init>(Login.java:31)
	at main.Main.main(Main.java:19)

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by jahentao** [comment]
为什么程序运行报错？空指针异常

**Comment by javaSunson** [comment]
the same quesstion 👍 
error:
Exception in thread "main" java.lang.NullPointerException
	at com.njupt.sms.ui.Login.<init>(Login.java:31)
	at Main.main(Main.java:18)

**Comment by leftjs** [comment]
@javaSunson 看看报错处，太久远的项目，记不得了

**Comment by nalanchenye** [comment]
Exception in thread "main" java.lang.NullPointerException
	at com.njupt.sms.ui.Login.<init>(Login.java:30)
	at Main.main(Main.java:18)


你好  运行报如上错误  应该是漏了代码

**Comment by leftjs** [comment]
#4

**Comment by leftjs** [comment]
#4   参照这个issue，用idea 运行

**Comment by nalanchenye** [comment]
@leftjs 您好，关于几个问题发了封邮件希望能够抽时间看一下。

**Comment by HappyCoderGS** [comment]
老哥，运行不起来啊，能不能写个在IDEA上怎么运行起来的教程，谢谢啊。这个项目有配套视频吗，想学习一下

**Comment by lanmhh** [comment]
@HappyCoderGS 同，请问你解决了吗？

**Comment by moneyDboat** [comment]
刚解决了这个问题，过来回复一下解决方法。
首先报空指针的原因是Login.java里的LoginButton按钮控件没有创建；解决方法是使用IDEA（作者使用IDEA的swing GUI编写界面，src->ui文件夹里后缀为.form的即为界面XML文件），然后确打开file->settings->Plugins里，搜索UI Designer，确保开启（没开启的勾选上，点Apply然后重启IDEA），完成之后选择运行Main.java即可
![image](https://user-images.githubusercontent.com/11391316/41817207-bd2b2cde-77c8-11e8-99f8-f874af4a3d0f.png)

**Comment by jahentao** [comment]
@moneyDboat 正解，我试了。IDEA通过该插件可以动态从form.xml组织界面，要改成eclipse可以运行，还需要从UI Designer生成代码。可以结案了。

**Comment by lanmhh** [comment]
你好，请问你能教教我这个项目在IDEA上怎么运行吗？

**Comment by jahentao** [comment]
@lanmhh 你遇到什么问题？

**Comment by Baconhhh** [comment]
Error: Unable to access jarfile G:\StudentGradesManageSystem-master\out\artifacts\StudentManagerSystem_jar\StudentManagerSystem.jar
请问遇到这种错误是什么问题？

**Comment by jahentao** [comment]
> Error: Unable to access jarfile G:\StudentGradesManageSystem-master\out\artifacts\StudentManagerSystem_jar\StudentManagerSystem.jar
> 请问遇到这种错误是什么问题？

我估计需要重新编译生成jar包，具体能详细点吗，说明操作下导致的，方便问题复现

**Comment by Baconhhh** [comment]
> > Error: Unable to access jarfile G:\StudentGradesManageSystem-master\out\artifacts\StudentManagerSystem_jar\StudentManagerSystem.jar
> > 请问遇到这种错误是什么问题？
> 
> 我估计需要重新编译生成jar包，具体能详细点吗，说明操作下导致的，方便问题复现

我已经解决啦，是我之前没有build成功导致的

**Comment by qingfeng55555** [comment]
![image](https://user-images.githubusercontent.com/50541145/58763076-36ec9980-8589-11e9-85ff-b53dc6b054a0.png)
请问这个问题怎么解决奥？添加学生信息的时候会报这个错，添加不上
